<?php

namespace Orkestro\Bundle\ProductBundle\Entity\Characteristic;

use Doctrine\ORM\EntityRepository;

/**
 * ValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValueRepository extends EntityRepository
{
}
