services:
  orkestro.manufacturer.configure_menu_listener:
    class: Orkestro\Bundle\ManufacturerBundle\EventListener\ConfigureMenuListener
    arguments: ["@translator"]
    tags:
      - { name: kernel.event_listener, event: orkestro.menu_builder.backend.main.configure, method: onMenuConfigure }