application:
  environment:
    php:
      version: 5.3.3
  project_setup:
    before:
      - mysql -uroot -e "CREATE DATABASE orkestro"
checks:
  php:
    code_rating: true
    duplication: true
filter:
  excluded_paths:
    - app/SymfonyRequirements.php