orkestro_backend_index:
  path: /
  defaults:
    _controller: FrameworkBundle:Redirect:redirect
    route: orkestro_backend_dashboard
    permanent: true

orkestro_backend_dashboard:
  resource: @OrkestroWebBundle/Controller/Backend/DashboardController.php
  type: annotation

orkestro_backend_category:
  resource: @OrkestroCategoryBundle/Controller/Backend/CategoryController.php
  type: annotation
  prefix: /category

orkestro_backend_country:
  resource: @OrkestroCountryBundle/Controller/Backend/CountryController.php
  type: annotation
  prefix: /country

orkestro_backend_locale:
  resource: @OrkestroLocaleBundle/Controller/Backend/LocaleController.php
  type: annotation
  prefix: /locale

orkestro_backend_manufacturer:
  resource: @OrkestroManufacturerBundle/Controller/Backend/ManufacturerController.php
  type: annotation
  prefix: /manufacturer
