orkestro_frontend:
  resource: @OrkestroWebBundle/Resources/config/routing/frontend.yml

orkestro_backend:
  resource: @OrkestroWebBundle/Resources/config/routing/backend.yml
  prefix: /admin

fos_user:
  resource: @FOSUserBundle/Resources/config/routing/all.xml
