orkestro_frontend:
  resource: @OrkestroWebBundle/Resources/config/routing/frontend.yml

orkestro_backend:
  resource: @OrkestroWebBundle/Resources/config/routing/backend.yml
  prefix: /backend

orkestro_authentication:
  resource: @OrkestroUserBundle/Resources/config/routing.yml
