parameters:
  orkestro_oauth_user_provider.class: Orkestro\Bundle\UserBundle\Security\Core\User\FOSUBUserProvider

services:
  orkestro_oauth_user_provider:
    class: "%orkestro_oauth_user_provider.class%"
    arguments: [@fos_user.user_manager, { facebook: facebookId, google: googleId }]

  orkestro.twig.social_expose_extension:
    class: Orkestro\Bundle\UserBundle\Twig\SocialExposeExtension
    arguments: ["@service_container"]
    tags:
      - { name: twig.extension }