hwi_oauth:
  connect:
    account_connector: orkestro_oauth_user_provider
  firewall_name: main
  fosub:
    username_iterations: 30
    properties:
      facebook: facebookId
      google: googleId
  resource_owners:
    facebook:
      type: facebook
      client_id: "%orkestro.oauth.facebook.app_id%"
      client_secret: "%orkestro.oauth.facebook.app_secret%"
      scope: "%orkestro.oauth.facebook.scope%"
    google:
      type: google
      client_id: "%orkestro.oauth.google.app_id%"
      client_secret: "%orkestro.oauth.google.app_secret%"
      scope: "%orkestro.oauth.google.scope%"
    vkontakte:
      type: vkontakte
      client_id: "%orkestro.oauth.vkontakte.app_id%"
      client_secret: "%orkestro.oauth.vkontakte.app_secret%"
      scope: "%orkestro.oauth.vkontakte.scope%"
    odnoklassniki:
      type: odnoklassniki
      client_id: "%orkestro.oauth.odnoklassniki.app_id%"
      client_secret: "%orkestro.oauth.odnoklassniki.app_secret%"
      scope: "%orkestro.oauth.odnoklassniki.scope%"