imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: includes/framework.yml }
    - { resource: includes/twig.yml }
    - { resource: includes/assetic.yml }
    - { resource: includes/doctrine.yml }
    - { resource: includes/swiftmailer.yml }
    - { resource: includes/fos_user.yml }
    - { resource: includes/hwi_oauth.yml }
