security:
  encoders:
    FOS\UserBundle\Model\UserInterface: sha512

  role_hierarchy:
    ROLE_ORKESTRO_ADMIN: ROLE_USER
    ROLE_SUPER_ADMIN: ROLE_ORKESTRO_ADMIN

  providers:
    fos_userbundle:
      id: fos_user.user_provider.username_email

  firewalls:
    dev:
      pattern:  ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      pattern: ^/
      form_login:
        provider: fos_userbundle
        csrf_provider: form.csrf_provider
        login_path: /login
        check_path: /login_check
        failure_path: /login
        default_target_path: /
      oauth:
        resource_owners:
          facebook: "/login/check-facebook"
          google: "/login/check-google"
          vkontakte: "/login/check-vkontakte"
          odnoklassniki: "/login/check-odnoklassniki"
        login_path: /login
        failure_path: /login
        oauth_user_provider:
          service: orkestro_oauth_user_provider
      logout:
        path: /logout
        target: /
      anonymous: true

  access_control:
    - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/login-check, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/backend/, role: ROLE_ORKESTRO_ADMIN }
