<?php

namespace Orkestro\Bundle\ProductBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductKindRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductKindRepository extends EntityRepository
{
}
