<?php

namespace Orkestro\Bundle\ManufacturerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ManufacturerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManufacturerRepository extends EntityRepository
{
}
